# Site-wide generic info (overridable per-page)
title: Guerrilla Ticket
description: Openly-licensed and completely unapproved resources to call out vehicle owners while supporting good causes
theme-color: "#ff7800"

# Settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
